import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { ABeeZee } from 'next/font/google'
import Header from "../components/header";

const inter=ABeeZee({
    subsets:['latin'],
    weight:"400"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<>
<Header/>
{children}
</>
  );
}
